# Import R packages needed for the UI
library(shiny)
library(shinycssloaders)
library(DT)
library(plotly)

# Begin UI for the R + reticulate example app
ui <- fluidPage(
  
  titlePanel('A simple ML app'),
  
  sidebarLayout(
    
    # ---------------- Sidebar panel with changeable inputs ----------------- #
    sidebarPanel(
      
      textInput('x_string',
                'Input',
                value = '-1.1, 1, 2, 3.14'),
      h5('Input the x values you want to make predictions from. E.g: 1, 2, 3.14159')
    ),
    
    # ---------------- Sidebar panel with changeable inputs ----------------- #
    mainPanel(
      
      # Output: Tabset w/ plot, summary, and table ----
      tabsetPanel(type = 'tabs',
                  tabPanel('Model predictions', 
                           br(),
                           plotlyOutput('plot', height="auto"),
                           br(),
                           h4('Outputs generated by the model from your input:'),
                           verbatimTextOutput('message'),
                           br()),
                  tabPanel('Extra info', 
                           h3("Wow, you've gotten quite far. I like your curiosity."),
                           hr()
                  )
      )
    )
  )
)